### ISSUE TITLE
Backend implementation TO-DO list

### ISSUE THREAD

**Issue by natinusala** [natinusala/NeoEMF#1]
## For `AbstractMongoDbBackend` :

- [x] `containerFor`
- [x] `metaClassFor`
- [x]  `containerOf`
- [x] `metaClassOf`
- [x] `allInstancesOf` (untested)
- [x] `removeContainer`

## For `DefaultMongoDbBackend` :

- [x] `referenceFor` single feature (untested)
- [x] `referenceFor` many features (untested)
- [x] `valueFor` single feature
- [x] `valueFor` many features
- [x] `addAllReferences`
- [x] `addAllValues`
- [x] `addReference`
- [x] `addValue`
- [x] `allReferencesOf`
- [x] `referenceOf` single feature
- [x] `referenceOf` many features
- [x] `sizeOfReference`
- [x] `sizeOfValue`
- [x] `removeAllReferences` single
- [x] `removeReference` many features
- [x] `removeReference` single feature (untested)
- [x] `removeValue` single feature
- [x] `removeValue` many features
- [x] `removeAllValues` (many features)
- [x] `valueOf` many features
- [x] `valueOf` single feature
- [x] `allValuesOf`
- [x] override append
# Other
- [x] replace naive arrays manipulation with database operations
- [x] fix broken URI tests
- [x] fix the maven non-bundle dependency warnings
- [ ] replace `remove / set` with `pull` in `removeValue`
